### ISSUE TITLE
1.18 version

### ISSUE THREAD

**Issue by orionSquared** [TBoshoven/MinecraftMods#108]
Good evening,

Love your mod and I'd love to add it to my new modpack but I noticed that your 1.18 mod version seems to be specific to 1.18.0. Is the mod compatible with 1.18.1/1.18.2? If so, can you mark it as such so I can add it to my modpack through curseforge?

Thanks

**Comment by TBoshoven** [comment]
Ah yes. Will do :+1:

**Comment by TBoshoven** [comment]
1.18.2 version was released a moment ago.
It looks like the 1.18 version doesn't work, so thanks for letting me know.

Please give it a shot and let me know if there are any issues.
