### ISSUE TITLE
door model not working

### ISSUE THREAD

**Issue by bob-the-fox** [TBoshoven/MinecraftMods#129]
![2023-07-16_15 45 28](https://github.com/TBoshoven/MinecraftMods/assets/107211243/f11603c9-cd29-4acd-b689-44a3dea2dd9d)
![2023-07-16_15 45 25](https://github.com/TBoshoven/MinecraftMods/assets/107211243/3a7b016c-38c7-4cac-ad14-e410f6eb5fa0)

**Comment by TBoshoven** [comment]
Thanks for the report!

Can you please let me know what version of the mod, Minecraft, and Forge you're using, so I can attempt to reproduce the issue? Thanks!

**Comment by bob-the-fox** [comment]
1.19.2 forge 43.2.18

**Comment by bob-the-fox** [comment]
> Thanks for the report!
> 
> Can you please let me know what version of the mod, Minecraft, and Forge you're using, so I can attempt to reproduce the issue? Thanks!

1.19.2
forge 43.2.18 
MagicDoorknob-1.19.2-1.1.0.678.jar

**Comment by TBoshoven** [comment]
![2023-08-05_14 54 34](https://github.com/TBoshoven/MinecraftMods/assets/1949124/926c2700-695d-4591-bb1d-478bd0cd0935)
I tried those versions (default settings on everything) and I could not reproduce the issue unfortunately.
It seems that it's likely some kind of interaction between mods. Are you running any performance or graphics mods (for example for shaders)?

**Comment by kyragit** [comment]
I also have this issue on 1.19.2. It's definitely a mod incompatibility, but my pack is large so I haven't found the culprit yet. I do know that it's definitely not any of these mods: canary, ebeddium/rubidium, fastsuite, ferritecore, immediatelyfast, lazydfu, lightspeed, moderfix, oculus, placebo, pluto, saturn, or starlight. I'll keep searching to try and find it, but if the original poster could send their modlist that would be appreciated :)

**Comment by kyragit** [comment]
Alright, I found the issue. It's an incompatibility with Create: Steam 'n' Rails. It has to do with a model mixin:
`[Render thread/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to bake model: 'magic_doorknob:magic_door#facing=north,part=top': java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.m_135827_()" because the return value of "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118413_()" is null`

I'm no expert but it looks like the mixin (`com.railwayteam.railways.mixin.client.MixinTextureAtlasSprite`) is interfering with your `TextureBakedModel` class somehow. Hopefully this helps fix it!

**Comment by TBoshoven** [comment]
Thank you very much @kyragit for narrowing this down!
I'm not sure if this is the exact same issue as @bob-the-fox was dealing with, but I'll reopen and assume it was :)

I have a suspicion about what it is.
It would technically be the other mod's fault. The value I'm thinking of is allowed to be `null`, but isn't really in practice. It's a very understandable issue, so I'll likely just work around it to prevent issues with other mods as well.

**Comment by TBoshoven** [comment]
Reproduced in 1.19.2.

**Comment by TBoshoven** [comment]
@kyragit I believe I fixed the issue.
It ended up being a different issue than I thought, and a rather fun bit of looking at mixins.

It seems like this particular issue was specific to 1.19.2. Later versions do not use the affected code.
I did end up backporting the fix all the way back to 1.15, as it ended up simplifying my textured model code somewhat.

Can you please try version [1.19.2-1.1.3](https://github.com/TBoshoven/MinecraftMods/releases/tag/magic-doorknob-1.19.2-1.1.3) (jar is on the release page and can also be found on CurseForge and Modrinth) and let me know if this did the trick?

**Comment by kyragit** [comment]
It works! Thanks so much for the quick fix!

**Comment by TBoshoven** [comment]
No problem! Thanks for the help tracking this down!
