### ISSUE TITLE
Torches Xray

### ISSUE THREAD

**Issue by WenXin20** [TBoshoven/MinecraftMods#22]
`Minecraft v1.15.2`
`Forge v31.2.5`
`Magic Door Knob v0.0.2.179`

The door can go through torches, which provides an x-ray effect. This probably works with other blocks too.

**Comment by TBoshoven** [comment]
Thank you for reporting.
I can reproduce the issue, only on 1.15.
![2020-06-02_21 05 26](https://user-images.githubusercontent.com/1949124/83584527-683dd380-a515-11ea-9ea2-c9481f45539b.png)
