### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by Illest8** [TBoshoven/MinecraftMods#292]
If anyone on my server leaves the server in proximity of the mirror, their game crashes.

**Comment by TBoshoven** [comment]
Thank you for reporting!
I'd love to try and reproduce this, so please let me know the following:

* What Minecraft version are you using?
* Do you happen to have a log from one of the affected clients?

**Comment by TBoshoven** [comment]
I managed to reproduce this in Minecraft 1.20.4 with no other mods.
Issue seems to be that the reflection renderer gets triggered after the world is unloaded.

The fix is simple. I'll have it out soon.

**Comment by TBoshoven** [comment]
Turns out this affected a lot of versions. Fixes going out soon.
