### ISSUE TITLE
Curse of Binding glitch.

### ISSUE THREAD

**Issue by user00003** [TBoshoven/MinecraftMods#52]
I was playing and noticed that, at least in the 1.12.2 version, you can remove curse of binding armor by swapping with the mirror and breaking it. I'm not sure if this is patched in later versions but I didn't think it would be.

**Comment by TBoshoven** [comment]
Interesting! I'm using some Forge utilities for serializing item stacks, but they might not handle this correctly.
Thanks for letting me know!

**Comment by TBoshoven** [comment]
Oh I now understand what you mean. Indeed, I am not handling this correctly.
Unfortunately there's no good way for me to fix this in 1.12, because I can no longer develop for that version.
However, I will try to implement a fix in later versions.

**Comment by TBoshoven** [comment]
Actually, let me keep this open for 1.12.2.

**Comment by TBoshoven** [comment]
Curiously, I was able to build the 1.12.2 version again, so I ended up fixing this there.
