### ISSUE TITLE
Banner Server Crash

### ISSUE THREAD

**Issue by WenXin20** [TBoshoven/MinecraftMods#58]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Magic Mirror v0.2.2.350`

After right-clicking the Magic Mirror with a Pillager Banner, my server immediately crashed.
[Crash Report](https://gist.github.com/WenXin20/ab8a69a3155b9544ad58c41dff2928ef)

**Comment by TBoshoven** [comment]
Ouch. Sorry about that.
I will investigate tonight.
I suspect there is some code that is running on the server that's intended to just run on the clients.

**Comment by WenXin20** [comment]
Thanks!

**Comment by TBoshoven** [comment]
Unfortunately I've had some trouble reproducing this issue, but I'm pretty sure I found the cause.
Going to release a fix now. @WenXin20, I would really appreciate it if you could verify whether this resolves the issue for you.

Let me keep this open pending feedback.

**Comment by WenXin20** [comment]
Sure! I'll see if I can give it a try tomorrow.

**Comment by WenXin20** [comment]
I was able to apply the banner without crashing, but when I broke the mirror, the server crashed.
[Crash Report](https://gist.github.com/WenXin20/332c8132d5a4b3c16b7d28e5cb1a92f3)

**Comment by TBoshoven** [comment]
Ugh. Okay I wonder why it's working for me... Might have to do with the way I have my testing environment set up.
Pretty sure I know the cause for this one as well. I'll try to get another fix out tonight.
Thanks for testing!

**Comment by TBoshoven** [comment]
So the method I'm using is `BannerBlock.forColor`, to spawn a banner of the right base color back into the world.
For some reason, this is marked for client-side use only. No idea why. Especially considering it's the only accessor of a map that is filled in both on clients and servers.

The workaround for this one is going to be quite annoying.

**Comment by TBoshoven** [comment]
I think I fixed the crash es for real now. If it's still happening, please let me know.

**Comment by WenXin20** [comment]
I haven't got anymore crashes, so it appears to be fixed. :)
