### ISSUE TITLE
[1.12.2-0.1.0.362] The Magic Mirror - Dedicated Server crash on startup. ClassNotFoundException.

### ISSUE THREAD

**Issue by JoelZBub** [TBoshoven/MinecraftMods#70]
Forge version : 1.12.2-14.23.5.2854
Magic Mirror Version : 1.12.2-0.1.0.362
No other mods installed.
Server crashes on startup with `ClassNotFoundException: com.tomboshoven.minecraft.magicmirror.blocks.tileentities.modifiers.MagicMirrorTileEntityModifierArmor$MessageHandlerEquipServer`

Crash Report Link: [https://hatebin.com/etppwustow](url)

**Comment by TBoshoven** [comment]
Interesting. Thanks for reporting!
I will try to look into this over the weekend.

**Comment by TBoshoven** [comment]
Oh wow, I completely missed writing that class :sweat_smile: 

I'm not sure why, but it's currently impossible to run a development server for 1.12.2, so I'm having a lot of trouble testing that unfortunately. I should have a fix in a few though.

**Comment by TBoshoven** [comment]
Please let me know if the new version works for you.
You can find it on CurseForge or [here](https://github.com/TBoshoven/MinecraftMods/releases/tag/magic-mirror-1.12.2-0.1.1).

**Comment by JoelZBub** [comment]
Unfortunately, the item and block with id `magic_mirror:magic_mirror` is not registering with the game once updated to this version.
The version uploaded to forge labeled as ` v1.12.2-0.1.1.428` is actually `MagicMirror-1.12.2-0.1.1.427-sources`
 Download

**Comment by JoelZBub** [comment]
Using the non-sources jar from the linked github releases page works great.

**Comment by TBoshoven** [comment]
I have no idea how the sources version made it into Curseforge.
Thank you very much for reporting this.

Only the 1.12.2 gradle build produces this jar, but so far it has never been selected for publishing to Curseforge.
I suppose the `ls` command I use might not sort the way I expected it to in Alpine...

I'll make sure to update with the correct file and fix my release script.
